### ISSUE TITLE
Won't compile!

### ISSUE THREAD

**Issue by rickrich** [audreyt/regex-genex#3]
$ make
cabal install
Resolving dependencies...
Configuring regex-genex-0.6.0...
Building regex-genex-0.6.0...
Preprocessing library regex-genex-0.6.0...
[3 of 3] Compiling Regex.Genex      ( src/Regex/Genex.hs, dist/build/Regex/Genex.o )

src/Regex/Genex.hs:176:27:
    Couldn't match expected type `Status -> Status'
                with actual type `Status'
    In the expression:
      Status
        {ok = symbolicMerge t (ok s1) (ok s2),
         pos = symbolicMerge t (pos s1) (pos s2),
         flips = symbolicMerge t (flips s1) (flips s2),
         captureAt = symbolicMerge t (captureAt s1) (captureAt s2),
         captureLen = symbolicMerge t (captureLen s1) (captureLen s2)}
    In an equation for `symbolicMerge':
        symbolicMerge t s1 s2
          = Status
              {ok = symbolicMerge t (ok s1) (ok s2),
               pos = symbolicMerge t (pos s1) (pos s2),
               flips = symbolicMerge t (flips s1) (flips s2),
               captureAt = symbolicMerge t (captureAt s1) (captureAt s2),
               captureLen = symbolicMerge t (captureLen s1) (captureLen s2)}
    In the instance declaration for `Mergeable Status'

src/Regex/Genex.hs:177:12:
    Couldn't match type `SBool -> SBool' with `SBV Bool'
    Expected type: SBool
      Actual type: SBool -> SBool
    In the return type of a call of `symbolicMerge'
    Probable cause: `symbolicMerge' is applied to too few arguments
    In the `ok' field of a record
    In the expression:
      Status
        {ok = symbolicMerge t (ok s1) (ok s2),
         pos = symbolicMerge t (pos s1) (pos s2),
         flips = symbolicMerge t (flips s1) (flips s2),
         captureAt = symbolicMerge t (captureAt s1) (captureAt s2),
         captureLen = symbolicMerge t (captureLen s1) (captureLen s2)}

src/Regex/Genex.hs:177:32:
    Couldn't match type `SBV Bool' with `Status'
    Expected type: Status
      Actual type: SBool
    In the first argument of `ok', namely `s1'
    In the second argument of `symbolicMerge', namely `(ok s1)'
    In the `ok' field of a record

src/Regex/Genex.hs:178:13:
    Couldn't match type `Offset -> Offset' with `SBV Len'
    Expected type: Offset
      Actual type: Offset -> Offset
    In the return type of a call of `symbolicMerge'
    Probable cause: `symbolicMerge' is applied to too few arguments
    In the `pos' field of a record
    In the expression:
      Status
        {ok = symbolicMerge t (ok s1) (ok s2),
         pos = symbolicMerge t (pos s1) (pos s2),
         flips = symbolicMerge t (flips s1) (flips s2),
         captureAt = symbolicMerge t (captureAt s1) (captureAt s2),
         captureLen = symbolicMerge t (captureLen s1) (captureLen s2)}

src/Regex/Genex.hs:178:30:
    Couldn't match type `Word16' with `Bool'
    Expected type: SBool
      Actual type: Offset
    In the return type of a call of `pos'
    In the second argument of `symbolicMerge', namely `(pos s1)'
    In the `pos' field of a record

src/Regex/Genex.hs:178:34:
    Couldn't match type `SBV Bool' with `Status'
    Expected type: Status
      Actual type: SBool
    In the first argument of `pos', namely `s1'
    In the second argument of `symbolicMerge', namely `(pos s1)'
    In the `pos' field of a record

src/Regex/Genex.hs:179:15:
    Couldn't match type `Flips -> Flips' with `[SWord64]'
    Expected type: Flips
      Actual type: Flips -> Flips
    In the return type of a call of `symbolicMerge'
    Probable cause: `symbolicMerge' is applied to too few arguments
    In the `flips' field of a record
    In the expression:
      Status
        {ok = symbolicMerge t (ok s1) (ok s2),
         pos = symbolicMerge t (pos s1) (pos s2),
         flips = symbolicMerge t (flips s1) (flips s2),
         captureAt = symbolicMerge t (captureAt s1) (captureAt s2),
         captureLen = symbolicMerge t (captureLen s1) (captureLen s2)}

src/Regex/Genex.hs:179:32:
    Couldn't match type `[SWord64]' with `SBV Bool'
    Expected type: SBool
      Actual type: Flips
    In the return type of a call of `flips'
    In the second argument of `symbolicMerge', namely `(flips s1)'
    In the `flips' field of a record

src/Regex/Genex.hs:179:38:
    Couldn't match type `SBV Bool' with `Status'
    Expected type: Status
      Actual type: SBool
    In the first argument of `flips', namely `s1'
    In the second argument of `symbolicMerge', namely `(flips s1)'
    In the `flips' field of a record

src/Regex/Genex.hs:180:19:
    Couldn't match type `Captures -> Captures'
                  with `SFunArray Word8 Len'
    Expected type: Captures
      Actual type: Captures -> Captures
    In the return type of a call of `symbolicMerge'
    Probable cause: `symbolicMerge' is applied to too few arguments
    In the `captureAt' field of a record
    In the expression:
      Status
        {ok = symbolicMerge t (ok s1) (ok s2),
         pos = symbolicMerge t (pos s1) (pos s2),
         flips = symbolicMerge t (flips s1) (flips s2),
         captureAt = symbolicMerge t (captureAt s1) (captureAt s2),
         captureLen = symbolicMerge t (captureLen s1) (captureLen s2)}

src/Regex/Genex.hs:180:36:
    Couldn't match type `SFunArray Word8 Len' with `SBV Bool'
    Expected type: SBool
      Actual type: Captures
    In the return type of a call of `captureAt'
    In the second argument of `symbolicMerge', namely `(captureAt s1)'
    In the `captureAt' field of a record

src/Regex/Genex.hs:180:46:
    Couldn't match type `SBV Bool' with `Status'
    Expected type: Status
      Actual type: SBool
    In the first argument of `captureAt', namely `s1'
    In the second argument of `symbolicMerge', namely `(captureAt s1)'
    In the `captureAt' field of a record

src/Regex/Genex.hs:181:20:
    Couldn't match type `Captures -> Captures'
                  with `SFunArray Word8 Len'
    Expected type: Captures
      Actual type: Captures -> Captures
    In the return type of a call of `symbolicMerge'
    Probable cause: `symbolicMerge' is applied to too few arguments
    In the `captureLen' field of a record
    In the expression:
      Status
        {ok = symbolicMerge t (ok s1) (ok s2),
         pos = symbolicMerge t (pos s1) (pos s2),
         flips = symbolicMerge t (flips s1) (flips s2),
         captureAt = symbolicMerge t (captureAt s1) (captureAt s2),
         captureLen = symbolicMerge t (captureLen s1) (captureLen s2)}

src/Regex/Genex.hs:181:37:
    Couldn't match type `SFunArray Word8 Len' with `SBV Bool'
    Expected type: SBool
      Actual type: Captures
    In the return type of a call of `captureLen'
    In the second argument of `symbolicMerge', namely `(captureLen s1)'
    In the `captureLen' field of a record

src/Regex/Genex.hs:181:48:
    Couldn't match type `SBV Bool' with `Status'
    Expected type: Status
      Actual type: SBool
    In the first argument of `captureLen', namely `s1'
    In the second argument of `symbolicMerge', namely `(captureLen s1)'
    In the `captureLen' field of a record
Failed to install regex-genex-0.6.0
cabal: Error: some packages failed to install:
regex-genex-0.6.0 failed during the building phase. The exception was:
ExitFailure 1
make: *** [install] Error 1

**Comment by audreyt** [comment]
Thanks for the report! It might be version drift against `sbv`.

Would you like to try changing the `regex-genex.cabal` file to say `sbv == 2.10` and build again? (or try `2.9` and `3.0` too to find where the breakage happens.)

**Comment by rickrich** [comment]
$ git pull
Already up-to-date.

$ cat regex-genex.cabal
Name            : regex-genex
Version         : 0.6.0
license         : OtherLicense
license-file    : LICENSE
cabal-version   : >= 1.6
copyright       : 2011-2013 Audrey Tang
maintainer      : Audrey Tang <audreyt@audreyt.org>
category        : Text, Regex
stability       : experimental
build-type      : Simple
homepage        : https://github.com/audreyt/regex-genex
synopsis        : From a regex, generate all possible strings it can match
description     : From a regex, generate all possible strings it can match
author          : Audrey Tang <audreyt@audreyt.org>
Tested-With:    GHC==7.0.2 GHC==7.4.1

library
    hs-source-dirs:     . src
    exposed-modules:    Regex.Genex Regex.Genex.Normalize
    other-modules:    Regex.Genex.Pure
    extensions      : ImplicitParams, NamedFieldPuns, ParallelListComp,
PatternGuards, RecordWildCards
    build-depends:
        base >= 3 && < 5, mtl, containers, sbv, regex-tdfa, stream-monad,
text, logict

executable genex
    main-is:            Main.hs
    hs-source-dirs:     . src
    extensions      : ImplicitParams, NamedFieldPuns, ParallelListComp,
PatternGuards, RecordWildCards
    build-depends:
        base >= 3 && < 5, mtl, containers, sbv, regex-tdfa

source-repository head
  type:     git
  location: http://github.com/audreyt/regex-genex

Where do I put it?


On Mon, Jan 19, 2015 at 5:50 AM, 唐鳳 <notifications@github.com> wrote:

> Thanks for the report! It might be version drift against sbv.
>
> Would you like to try changing the regex-genex.cabal file to say sbv ==
> 2.10 and build again? (or try 2.9 and 3.0 too to find where the breakage
> happens.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/audreyt/regex-genex/issues/3#issuecomment-70481882>.
>



-- 
Rick Richardson rickrich@gmail.com http://rickrich1.home.comcast.net/
Linux printer drivers for JBIG (GDI printers): Konica Minolta magicolor,
                          HP LaserJet, Samsung, Xerox, Lexmark, and Oki.
                                             http://foo2zjs.rkkda.com/
Linux tools for geocaching   http://geo.rkkda.com/
Gnome Manual Duplex         http://sourceforge.net/projects/g-manual-duplex/

**Comment by rickrich** [comment]
Thanks!

On Mon, Jan 19, 2015 at 6:49 AM, 唐鳳 <notifications@github.com> wrote:

> Closed #3 <https://github.com/audreyt/regex-genex/issues/3> via a31eb7a
> <https://github.com/audreyt/regex-genex/commit/a31eb7ade54f48ff157fc72cd3c196f40c863ef5>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/audreyt/regex-genex/issues/3#event-220948245>.
>



-- 
Rick Richardson rickrich@gmail.com http://rickrich1.home.comcast.net/
Linux printer drivers for JBIG (GDI printers): Konica Minolta magicolor,
                          HP LaserJet, Samsung, Xerox, Lexmark, and Oki.
                                             http://foo2zjs.rkkda.com/
Linux tools for geocaching   http://geo.rkkda.com/
Gnome Manual Duplex         http://sourceforge.net/projects/g-manual-duplex/
